vich_uploader:
    db_driver: orm

    mappings:
        img_avatar:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
